#!/bin/sh

path=/etc/crontab

sudo mv checknew checkold
sudo md5sum $path > ./checknew
CHECKSUM=$(diff checknew checkold)

if [ "x$CHECKSUM" != "x" ]; then
	echo "Automated regards" | mail -s "Le fichier Crontab a ete modifie" root@localhost
fi
