#!/bin/sh

path=/etc/crontab
store=/var/log

sudo touch $store/checknew

sudo mv $store/checknew $store/checkold
sudo md5sum $path > .$store/checknew

CHECKSUM=$(sudo diff $store/checknew $store/checkold)

if [ "s$CHECKSUM" != "s" ]; then
	echo "Automated regards" | mail -s "Le fichier Crontab a ete modifie" root@localhost
fi
